# Generated by Django 5.2.5 on 2025-09-02 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('funcao', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_epi', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade_total', models.PositiveIntegerField(default=0)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('devolvido', models.BooleanField(default=False)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
            ],
        ),
    ]
