# Generated by Django 5.2.5 on 2025-09-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade_devolvida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade_emprestada',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
